services:
  # excalimat-backend-lr:
  #   image: acim/go-reflex
  #   volumes:
  #     - ../../:/app
  #   ports:
  #     - 3000:3000
  #   tty: true
  #   environment:
  #     - RACE_DETECTOR=1
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
  minio:
    image: quay.io/minio/minio:RELEASE.2022-03-17T06-34-49Z
    command: server --console-address ":9001" /data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
