services:
  # excalimat-backend-lr:
  #   image: acim/go-reflex
  #   volumes:
  #     - ../../:/app
  #   ports:
  #     - 3000:3000
  #   tty: true
  #   environment:
  #     - RACE_DETECTOR=1
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
